# fly.toml app configuration file generated for autumn-wood-4029 on 2023-05-02T11:55:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-wood-4029"
primary_region = "bog"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
